### ISSUE TITLE
How can I draw canvas on cameraTextureView

### ISSUE THREAD

**Issue by hasanAjsf** [husaynhakeem/android-camerax-sample#2]
Hi Husayn,
This is not direct question for your example, but request of help if you can, thanks.
I tried below but nothing happened:
```kotlin
val paint = Paint().apply {
             isAntiAlias = true
             style = Paint.Style.STROKE
             color = Color.RED
            strokeWidth = 10f
}

var canvas = Canvas(bitmap) 
canvas.drawRect(
           rect.x.toFloat(),
           rect.y.toFloat(), 
           rect.x.toFloat() + rect.width,
          rect.y.toFloat() + rect.height,
)

cameraTextureView.unlockCanvasAndPost(canvas)
```

**Comment by husaynhakeem** [comment]
Hey @hajsf. Sorry for the late reply, just saw your comment. If you're still interested, you can take a look at [this article](https://www.bignerdranch.com/blog/using-firebasemlkit-with-camerax/), it implements exactly what you're looking to do.
